CREATE TABLE IF NOT EXISTS T_CONN (
	ID VARCHAR(36) PRIMARY KEY,
	DB_TYPE VARCHAR(64),
	PARENT_ID VARCHAR(36),
	NAME VARCHAR(64),
	USER VARCHAR(64),
	PWD VARCHAR(256),
	URL VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS T_POWER (
	ID VARCHAR(36) PRIMARY KEY,
	ROLE_ID VARCHAR(36),
	CONN_ID VARCHAR(36)
);

CREATE TABLE IF NOT EXISTS T_ROLE (
	ID VARCHAR(36) PRIMARY KEY,
	NAME VARCHAR(64)
);

INSERT INTO T_ROLE (
	ID,
	NAME
) VALUES (
	'1',
	'admin'
);

CREATE TABLE IF NOT EXISTS T_TREE (
	ID VARCHAR(36) PRIMARY KEY,
	LABEL VARCHAR(64),
	PARENT VARCHAR(36)
);

CREATE TABLE IF NOT EXISTS T_USER (
	ID VARCHAR(36) PRIMARY KEY,
	LOGIN_NAME VARCHAR(64),
	NAME VARCHAR(64),
	PWD VARCHAR(256)
);

-- 管理员id一定是 1
INSERT INTO T_USER (
	ID,
	LOGIN_NAME,
	NAME,
	PWD
) VALUES (
	'1',
	'admin',
	'管理员',
	'7e2e1f2e1eb71a6f7915a96201237ff0'
);

CREATE TABLE IF NOT EXISTS T_USER_ROLE (
	ID VARCHAR(36) PRIMARY KEY,
	USER_ID BIGINT,
	ROLE_ID BIGINT
);

INSERT INTO T_USER_ROLE (
	ID,
	USER_ID,
	ROLE_ID
) VALUES (
	'1',
	'1',
	'1'
);